apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-statefulset
spec:
  serviceName: kafka-service
  replicas: 1
  minReadySeconds: 120
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:7.4.4
          ports:
            - containerPort: 9091
            - containerPort: 9092
          volumeMounts:
            - name: kafka-volume
              mountPath: /var/lib/kafka
          env:
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "BROKER://:9091"
            - name: KAFKA_LISTENERS
              value: "BROKER://0.0.0.0:9091, CONTROLLER://0.0.0.0:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "BROKER"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG4J_ROOT_LOGLEVEL
              value: "WARN"
            - name: KAFKA_LOG4J_LOGGERS
              value: "org.apache.zookeeper=WARN,org.apache.kafka=WARN,kafka=WARN,kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN"
          readinessProbe:
            tcpSocket:
              port: 9091
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 60
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "sh /bin/kafka-broker-api-versions --bootstrap-server=localhost:9091"
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        storageClassName: kafka-volume
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-volume
spec:
  storageClassName: kafka-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/micromarket/kafka"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  type: NodePort
  selector:
    name: kafka
  ports:
    - port: 9091
      name: port0
    - port: 9092
      name: port1