apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: kafkaconnect-redis
  labels:
    strimzi.io/cluster: kafkaconnect
spec:
  class: com.redis.kafka.connect.RedisSinkConnector
  tasksMax: 2
  config:
    connector.class: com.redis.kafka.connect.RedisSinkConnector
    topics.regex: entity.(.*)
    redis.uri: redis://redis-master:6379
    redis.command: SET
    redis.separator: "::"
    redis.password: "redis"
    consumer.fetch.max.wait.ms: 50
    consumer.fetch.min.bytes: 1048576
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter.schemas.enable: false