apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
spec:
  replicas: 1
  minReadySeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: orderservice
  template:
    metadata:
      labels:
        name: orderservice
    spec:
      containers:
        - name: orderservice-container
          image: slow3586/micromarket:orderservice-0.1.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- range .Values.springEnv }}
            - name: {{ .name }}
              value: "{{.value}}"
            {{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
  labels:
    name: orderservice
spec:
  type: NodePort
  selector:
    name: orderservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web