apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockservice-deployment
spec:
  replicas: 1
  minReadySeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: stockservice
  template:
    metadata:
      labels:
        name: stockservice
    spec:
      containers:
        - name: stockservice-container
          image: slow3586/micromarket:stockservice-0.2.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- range .Values.springEnv }}
            - name: {{ .name }}
              value: "{{.value}}"
            {{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: stockservice-service
  labels:
    name: stockservice
spec:
  type: LoadBalancer
  selector:
    name: stockservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web