apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1
  minReadySeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: userservice
  template:
    metadata:
      labels:
        name: userservice
    spec:
      containers:
        - name: userservice-container
          image: slow3586/micromarket:userservice-0.1.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- range .Values.springEnv }}
            - name: {{ .name }}
              value: "{{.value}}"
            {{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    name: userservice
spec:
  type: NodePort
  selector:
    name: userservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web