imagePullPolicy: Always
springEnv:
  - name: server.port
    value: "8080"
  - name: KAFKA_SERVERS
    value: "kafka-controller-headless:9092"
  - name: spring.datasource.url
    value: "jdbc:postgresql://postgres-postgresql-hl:5432/postgres"
  - name: spring.liquibase.url
    value: "jdbc:postgresql://postgres-postgresql-hl:5432/postgres"
  - name: spring.data.redis.host
    value: "redis-master"
  - name: management.tracing.enabled
    value: "true"
  - name: management.otlp.tracing.endpoint
    value: "http://jaeger-service:14250"
  - name: SECRET_KEY
    value: "qweqweqweqweqweqweqweqweqweqweqrqwrqwrtweqtewqtweq"
  - name: API_KEY
    value: "qwtiuqwtiuqiwutiqwitiqwutiqwuituqwiotuqiowutiq"
  - name: app.client.balance
    value: "http://balanceservice-service:8080"
  - name: app.client.delivery
    value: "http://deliveryservice-service:8080"
  - name: app.client.notification
    value: "http://notificationservice-service:8080"
  - name: app.client.order
    value: "http://orderservice-service:8080"
  - name: app.client.product
    value: "http://productservice-service:8080"
  - name: app.client.stock
    value: "http://stockservice-service:8080"
  - name: app.client.user
    value: "http://userservice-service:8080"